// Generated by gencpp from file mpc_msgs/ControlCommand.msg
// DO NOT EDIT!


#ifndef MPC_MSGS_MESSAGE_CONTROLCOMMAND_H
#define MPC_MSGS_MESSAGE_CONTROLCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mpc_msgs
{
template <class ContainerAllocator>
struct ControlCommand_
{
  typedef ControlCommand_<ContainerAllocator> Type;

  ControlCommand_()
    : linear_velocity(0.0)
    , linear_acceleration(0.0)
    , steering_angle(0.0)  {
    }
  ControlCommand_(const ContainerAllocator& _alloc)
    : linear_velocity(0.0)
    , linear_acceleration(0.0)
    , steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef float _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef float _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::mpc_msgs::ControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpc_msgs::ControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommand_

typedef ::mpc_msgs::ControlCommand_<std::allocator<void> > ControlCommand;

typedef boost::shared_ptr< ::mpc_msgs::ControlCommand > ControlCommandPtr;
typedef boost::shared_ptr< ::mpc_msgs::ControlCommand const> ControlCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpc_msgs::ControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpc_msgs::ControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mpc_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::mpc_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return lhs.linear_velocity == rhs.linear_velocity &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mpc_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::mpc_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mpc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_msgs::ControlCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f18688373335fc84f514359a96a6319d";
  }

  static const char* value(const ::mpc_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf18688373335fc84ULL;
  static const uint64_t static_value2 = 0xf514359a96a6319dULL;
};

template<class ContainerAllocator>
struct DataType< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpc_msgs/ControlCommand";
  }

  static const char* value(const ::mpc_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linear_velocity\n"
"float32 linear_acceleration #m/s^2\n"
"float32 steering_angle\n"
;
  }

  static const char* value(const ::mpc_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_velocity);
      stream.next(m.linear_acceleration);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpc_msgs::ControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpc_msgs::ControlCommand_<ContainerAllocator>& v)
  {
    s << indent << "linear_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "linear_acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPC_MSGS_MESSAGE_CONTROLCOMMAND_H
