// Generated by gencpp from file mpc_msgs/TaskControl.msg
// DO NOT EDIT!


#ifndef MPC_MSGS_MESSAGE_TASKCONTROL_H
#define MPC_MSGS_MESSAGE_TASKCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mpc_msgs
{
template <class ContainerAllocator>
struct TaskControl_
{
  typedef TaskControl_<ContainerAllocator> Type;

  TaskControl_()
    : traj_end(0)
    , traj_turn(0)  {
    }
  TaskControl_(const ContainerAllocator& _alloc)
    : traj_end(0)
    , traj_turn(0)  {
  (void)_alloc;
    }



   typedef uint8_t _traj_end_type;
  _traj_end_type traj_end;

   typedef uint8_t _traj_turn_type;
  _traj_turn_type traj_turn;





  typedef boost::shared_ptr< ::mpc_msgs::TaskControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpc_msgs::TaskControl_<ContainerAllocator> const> ConstPtr;

}; // struct TaskControl_

typedef ::mpc_msgs::TaskControl_<std::allocator<void> > TaskControl;

typedef boost::shared_ptr< ::mpc_msgs::TaskControl > TaskControlPtr;
typedef boost::shared_ptr< ::mpc_msgs::TaskControl const> TaskControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpc_msgs::TaskControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpc_msgs::TaskControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mpc_msgs::TaskControl_<ContainerAllocator1> & lhs, const ::mpc_msgs::TaskControl_<ContainerAllocator2> & rhs)
{
  return lhs.traj_end == rhs.traj_end &&
    lhs.traj_turn == rhs.traj_turn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mpc_msgs::TaskControl_<ContainerAllocator1> & lhs, const ::mpc_msgs::TaskControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mpc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mpc_msgs::TaskControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc_msgs::TaskControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc_msgs::TaskControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc_msgs::TaskControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_msgs::TaskControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc_msgs::TaskControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpc_msgs::TaskControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc711d3525457fc9a0066f50f991e5eb";
  }

  static const char* value(const ::mpc_msgs::TaskControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc711d3525457fc9ULL;
  static const uint64_t static_value2 = 0xa0066f50f991e5ebULL;
};

template<class ContainerAllocator>
struct DataType< ::mpc_msgs::TaskControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpc_msgs/TaskControl";
  }

  static const char* value(const ::mpc_msgs::TaskControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpc_msgs::TaskControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 traj_end\n"
"uint8 traj_turn\n"
;
  }

  static const char* value(const ::mpc_msgs::TaskControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpc_msgs::TaskControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj_end);
      stream.next(m.traj_turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpc_msgs::TaskControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpc_msgs::TaskControl_<ContainerAllocator>& v)
  {
    s << indent << "traj_end: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.traj_end);
    s << indent << "traj_turn: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.traj_turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPC_MSGS_MESSAGE_TASKCONTROL_H
