// Generated by gencpp from file behaviour_state_machine/GoalPoseResponse.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_STATE_MACHINE_MESSAGE_GOALPOSERESPONSE_H
#define BEHAVIOUR_STATE_MACHINE_MESSAGE_GOALPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mpc_msgs/Lane.h>

namespace behaviour_state_machine
{
template <class ContainerAllocator>
struct GoalPoseResponse_
{
  typedef GoalPoseResponse_<ContainerAllocator> Type;

  GoalPoseResponse_()
    : is_success(false)
    , traj()  {
    }
  GoalPoseResponse_(const ContainerAllocator& _alloc)
    : is_success(false)
    , traj(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_success_type;
  _is_success_type is_success;

   typedef  ::mpc_msgs::Lane_<ContainerAllocator>  _traj_type;
  _traj_type traj;





  typedef boost::shared_ptr< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoalPoseResponse_

typedef ::behaviour_state_machine::GoalPoseResponse_<std::allocator<void> > GoalPoseResponse;

typedef boost::shared_ptr< ::behaviour_state_machine::GoalPoseResponse > GoalPoseResponsePtr;
typedef boost::shared_ptr< ::behaviour_state_machine::GoalPoseResponse const> GoalPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator1> & lhs, const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_success == rhs.is_success &&
    lhs.traj == rhs.traj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator1> & lhs, const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour_state_machine

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e1d92b8f22c17c1e9e4839abb91044a";
  }

  static const char* value(const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e1d92b8f22c17c1ULL;
  static const uint64_t static_value2 = 0xe9e4839abb91044aULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_state_machine/GoalPoseResponse";
  }

  static const char* value(const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_success\n"
"mpc_msgs/Lane traj\n"
"\n"
"================================================================================\n"
"MSG: mpc_msgs/Lane\n"
"Header header\n"
"int32 increment\n"
"int32 lane_id\n"
"Waypoint[] waypoints\n"
"\n"
"uint32 lane_index\n"
"float32 cost\n"
"float32 closest_object_distance\n"
"float32 closest_object_velocity\n"
"bool is_blocked\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mpc_msgs/Waypoint\n"
"# global id\n"
"int32 gid \n"
"# local id\n"
"int32 lid\n"
"geometry_msgs/PoseStamped pose\n"
"geometry_msgs/TwistStamped twist\n"
"int32 change_flag\n"
"\n"
"uint32 lane_id\n"
"uint32 left_lane_id\n"
"uint32 right_lane_id\n"
"uint32 stop_line_id\n"
"float32 cost\n"
"float32 time_cost\n"
"\n"
"# Lane Direction\n"
"# FORWARD				= 0\n"
"# FORWARD_LEFT	 		= 1\n"
"# FORWARD_RIGHT			= 2\n"
"# BACKWARD				= 3 \n"
"# BACKWARD_LEFT			= 4\n"
"# BACKWARD_RIGHT		= 5\n"
"# STANDSTILL	 		= 6\n"
"uint32 direction\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistStamped\n"
"# A twist with reference coordinate frame and timestamp\n"
"Header header\n"
"Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_success);
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour_state_machine::GoalPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_success);
    s << indent << "traj: ";
    s << std::endl;
    Printer< ::mpc_msgs::Lane_<ContainerAllocator> >::stream(s, indent + "  ", v.traj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_STATE_MACHINE_MESSAGE_GOALPOSERESPONSE_H
